
name: CI/CD

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Get GitHub Actions IP
        id: ip
        uses: haythem/public-ip@v1.2

      - name : Setting NCP CLI & Credentials
        run: |
          wget https://www.gov-ncloud.com/api/support/download/files/cli/GOV_CLI_1.1.18_20240222.zip -O ncloud_cli.zip
          unzip ncloud_cli.zip -d ~/cli_linux
          mkdir -p ~/.ncloud
          echo -e "[DEFAULT]\nncloud_access_key_id = ${{ secrets.NCP_ACCESS_KEY }}\nncloud_secret_access_key = ${{ secrets.NCP_SECRET_KEY }}\nncloud_api_url = ${{ secrets.NCP_API_URL }}" > ~/.ncloud/configure

      - name: Verify ncloud CLI Installation
        run: |
          ls -l ~/cli_linux
          find ~/cli_linux -name "ncloud"

      - name: Check ncloud configure
        run: |
          cd ~/.ncloud
          cat configure

      - name: Add Github Action Ip to Security group
        run: |
          chmod -R 777 ~/cli_linux/GOV_CLI_1.1.18_20240222/cli_linux
          cd ~/cli_linux/GOV_CLI_1.1.18_20240222/cli_linux
          chmod +x ncloud
          chmod +x ./jre8/bin/java
          ./ncloud vserver addAccessControlGroupInboundRule --regionCode KR --vpcNo ${{ secrets.NCP_VPC_NO }} --accessControlGroupNo ${{ secrets.NCP_ACG_NO }} --accessControlGroupRuleList "protocolTypeCode='TCP', ipBlock='${{ steps.ip.outputs.ipv4 }}/32', portRange='${{ secrets.SSH_PORT }}'" "protocolTypeCode='TCP', ipBlock='0.0.0.0/0', portRange='8080'"
          
          sleep 30

      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.NCP_HOST }}
          username: ${{ secrets.NCP_USERNAME }}
          password: ${{ secrets.NCP_PASSWORD }}
          port: ${{ secrets.NCP_PORT }}
          script: |
            cd ~/study-together-project/study-together
            ./deploy.sh

      - name: Remove GitHub Action Ip to Security group
        run: |
          chmod -R 777 ~/cli_linux/GOV_CLI_1.1.18_20240222/cli_linux
          cd ~/cli_linux/GOV_CLI_1.1.18_20240222/cli_linux
          ./ncloud vserver removeAccessControlGroupInboundRule --regionCode KR --vpcNo ${{ secrets.NCP_VPC_NO }} --accessControlGroupNo ${{ secrets.NCP_ACG_NO }} --accessControlGroupRuleList "protocolTypeCode='TCP', ipBlock='${{ steps.ip.outputs.ipv4 }}/32', portRange='${{ secrets.SSH_PORT }}'" 
